feat: Update Helm charts release workflow with improved configurations and dependencies

diff --git a/workflow-templates/helm-charts-release.yaml b/workflow-templates/helm-charts-release.yaml
--- a/workflow-templates/helm-charts-release.yaml
+++ b/workflow-templates/helm-charts-release.yaml
@@ -7,6 +7,7 @@
 # The workflow uses the `netcracker/qubership-workflow-hub/actions/helm-charts-release` action to perform the release steps.
 # The workflow requires the following inputs:
 # - `release`: The release version to publish.
+# The workflow requires several configuration files:
 # - configuration file used for the release process: `.github/helm-charts-release-config.yaml`
 #   Example: config/examples/helm-charts-release-config.yaml
 # - Docker build configuration file: `.github/docker-build-config.json`
@@ -21,7 +22,7 @@ on:
   workflow_dispatch:
     inputs:
       release:
-        description: 'Release version'
+        description: 'Release version. SemVer.'
         required: true
         type: string
 permissions:
@@ -29,15 +30,15 @@ permissions:
   packages: write
 run-name: ${{ github.repository }} Release ${{ github.event.inputs.release }}
 concurrency:
-  group: 'helm-charts-release'
-  cancel-in-progress: false
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 jobs:
   check-tag:
     runs-on: ubuntu-latest
     steps:
       - name: Check if tag exists
         id: check_tag
-        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.1
+        uses: netcracker/qubership-workflow-hub/actions/tag-action@main
         with:
           tag-name: 'v${{ inputs.release }}'
           ref: ${{ github.ref }}
@@ -47,110 +48,41 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   load-docker-build-components:
-    needs: [check-tag]
     runs-on: ubuntu-latest
     outputs:
       component: ${{ steps.load_component.outputs.components }}
       platforms: ${{ steps.load_component.outputs.platforms }}
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Load Docker Configuration
-        id: load_component
-        run:  |
-          verify=$(cat "$GITHUB_WORKSPACE/.github/docker-build-config.json" | jq '
-          def verify_structure:
-          .components as $components
-          | .platforms as $platforms
-          | ($components | type == "array")
-          and (all($components[]; has("name") and has("file") and has("context")))
-          and ($platforms | type == "string");
-          verify_structure
-          | if . then true else false end
-          ')
-          if [ ${verify} == 'true' ]; then
-            echo "✅ $GITHUB_WORKSPACE/.github/docker-build-config.json file is valid"
-            components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
-            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
-          else
-            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid"
-            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
-            exit 1
-          fi
-          echo "components=${components}" >> $GITHUB_OUTPUT
-          echo "platforms=${platforms}" >> $GITHUB_OUTPUT
+    - name: Load Docker Configuration
+      id: load_component
+      run:  |
+        verify=$(cat "$GITHUB_WORKSPACE/.github/docker-build-config.json" | jq '
+        def verify_structure:
+        .components as $components
+        | .platforms as $platforms
+        | ($components | type == "array")
+        and (all($components[]; has("name") and has("file") and has("context")))
+        and ($platforms | type == "string");
+        verify_structure
+        | if . then true else false end
+        ')
+        if [ ${verify} == 'true' ]; then
+          echo "✅ $GITHUB_WORKSPACE/.github/docker-build-config.json file is valid"
+          components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+          platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+        else
+          echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid"
+          echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
+          exit 1
+        fi
+        echo "components=${components}" >> $GITHUB_OUTPUT
+        echo "platforms=${platforms}" >> $GITHUB_OUTPUT
 
   docker-check-build:
-    needs: [load-docker-build-components]
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: true
-      matrix:
-        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
-    steps:
-      - name: Debug
-        run: |
-          echo "Component name: ${{ matrix.component.name }}"
-          echo "Component file: ${{ matrix.component.file }}"
-          echo "Component context: ${{ matrix.component.context }}"
-          echo "Platforms: ${{ needs.load-docker-build-components.outputs.platforms }}"
-      - name: Docker check build
-        id: docker-check-build
-        uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.1
-        with:
-          ref: ${{ github.ref }}
-          download-artifact: false
-          dry-run: true
-          component: ${{ toJson(matrix.component) }}
-          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
-          tags: "test-${{ inputs.release }}"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  chart-release:
-    needs: [docker-check-build, check-tag, load-docker-build-components]
-    runs-on: ubuntu-latest
-    outputs:
-      images-versions: ${{ steps.update-versions.outputs.images-versions }}
-    steps:
-      - name: "Prepare app token"
-        uses: actions/create-github-app-token@v1
-        id: app-token
-        with:
-          app-id: ${{ vars.GH_BUMP_VERSION_APP_ID }}
-          private-key: ${{ secrets.GH_BUMP_VERSION_APP_KEY }}
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          token: ${{ steps.app-token.outputs.token }}
-
-      - name: "Update versions in values"
-        id: update-versions
-        uses: netcracker/qubership-workflow-hub/actions/helm-charts-release@v1.0.1
-        with:
-          release-version: ${{ inputs.release }}
-          config-file: .github/helm-charts-release-config.yaml
-        env:
-          ${{ insert }}: ${{ vars }}
-
-      - name: "Debug"
-        run: |
-          echo "Images versions: ${{ steps.update-versions.outputs.images-versions }}"
-  tag:
-    needs: [chart-release]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Create release tag
-        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.1
-        with:
-          tag-name: "v${{ inputs.release }}"
-          ref: "release-${{ inputs.release }}"
-          create-tag: true
-          check-tag: false
-
-  docker-build:
-    needs: [tag, load-docker-build-components, chart-release]
+    needs: [load-docker-build-components, check-tag]
     runs-on: ubuntu-latest
     strategy:
       fail-fast: true
@@ -160,9 +92,65 @@ jobs:
       - name: Get version for current component
         id: get-version
         run: |
-          echo "IMAGE_VERSION=${{ fromJson(needs.chart-release.outputs.images-versions)[matrix.component.name] || inputs.release }}" >> $GITHUB_ENV
+          echo "IMAGE=${{ matrix.component.name }}" >> $GITHUB_ENV
       - name: Docker build
-        uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.1
+        uses: netcracker/qubership-workflow-hub/actions/docker-action@main
+        with:
+          ref: ${{ github.ref }}
+          download-artifact: false
+          dry-run: true
+          component: ${{ toJson(matrix.component) }}
+          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
+          tags: "${{ env.IMAGE_VERSION }}"
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+  chart-release-prepare:
+    needs: [check-tag, load-docker-build-components, docker-check-build]
+    runs-on: ubuntu-latest
+    outputs:
+      images-versions: ${{ steps.update-versions.outputs.images-versions }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: "Update versions in values"
+        id: update-versions
+        uses: netcracker/qubership-workflow-hub/actions/helm-charts-release@main
+        with:
+          release-version: ${{ inputs.release }}
+          config-file: .github/helm-charts-release-config.yaml
+        env:
+          ${{ insert }}: ${{ vars }}
+      - name: "Debug"
+        run: |
+          echo "Images versions: ${{ steps.update-versions.outputs.images-versions }}"
+  tag:
+    needs: [chart-release-prepare]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Create release tag
+        uses: netcracker/qubership-workflow-hub/actions/tag-action@main
+        with:
+          tag-name: "v${{ inputs.release }}"
+          ref: "release-${{ inputs.release }}"
+          create-tag: true
+          check-tag: false
+  docker-build:
+    needs: [tag, chart-release-prepare, load-docker-build-components]
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+      matrix:
+        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
+    steps:
+      - name: Get version for current component
+        id: get-version
+        run: |
+          echo "IMAGE_VERSION=${{ fromJson(needs.chart-release-prepare.outputs.images-versions)[matrix.component.name] || inputs.release }}" >> $GITHUB_ENV
+
+      - name: Docker build
+        uses: netcracker/qubership-workflow-hub/actions/docker-action@main
         with:
           ref: v${{ inputs.release }}
           download-artifact: false
@@ -173,15 +161,42 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ github.token }}
 
-  github-release:
-    needs: [docker-build]
-    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@v1.0.1
-    with:
-      version: ${{ inputs.release }}
-      publish: true
+  charts-release:
+    needs: [tag, docker-build]
+    continue-on-error: true
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: release-${{ inputs.release }}
 
+      - name: Configure Git
+        run: |
+          git config user.name "$GITHUB_ACTOR"
+          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+
+      - name: Run chart-releaser
+        uses: netcracker/chart-releaser-action@main
+        with:
+          charts_dir: charts/helm
+          release_name_template: "v{{ .Version }}"
+        env:
+          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+
+      - name: "Release-drafter"
+        uses: netcracker/release-drafter@master
+        with:
+          config-name: release-drafter-config.yml
+          publish: true
+          name: ${{ inputs.release }}
+          tag: v${{ inputs.release }}
+          version: v${{ inputs.release }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   upload-assets:
-    needs: [github-release]
+    needs: [charts-release]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -190,7 +205,7 @@ jobs:
           ref: v${{ inputs.release }}
 
       - name: Archive and Upload Assets
-        uses: netcracker/qubership-workflow-hub/actions/archive-and-upload-assets@v1.0.1
+        uses: netcracker/qubership-workflow-hub/actions/archive-and-upload-assets@main
         with:
           config-path: './.github/assets-config.yml'
           dist-path: './dist'
