Update helm-charts-release.yaml (#88)
* Update helm-charts-release.yaml

* chore: update helm-charts-release.yaml

diff --git a/workflow-templates/helm-charts-release.yaml b/workflow-templates/helm-charts-release.yaml
--- a/workflow-templates/helm-charts-release.yaml
+++ b/workflow-templates/helm-charts-release.yaml
@@ -22,9 +22,10 @@ on:
   workflow_dispatch:
     inputs:
       release:
-        description: 'Release version. SemVer.'
+        description: 'Release version'
         required: true
         type: string
+
 permissions:
   contents: write
   packages: write
@@ -32,6 +33,7 @@ run-name: ${{ github.repository }} Release ${{ github.event.inputs.release }}
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
+
 jobs:
   check-tag:
     runs-on: ubuntu-latest
@@ -40,7 +42,7 @@ jobs:
         id: check_tag
         uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.3
         with:
-          tag-name: 'v${{ inputs.release }}'
+          tag-name: '${{ inputs.release }}'
           ref: ${{ github.ref }}
           create-tag: false
           check-tag: true
@@ -53,33 +55,33 @@ jobs:
       component: ${{ steps.load_component.outputs.components }}
       platforms: ${{ steps.load_component.outputs.platforms }}
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Load Docker Configuration
-      id: load_component
-      run:  |
-        verify=$(cat "$GITHUB_WORKSPACE/.github/docker-build-config.json" | jq '
-        def verify_structure:
-        .components as $components
-        | .platforms as $platforms
-        | ($components | type == "array")
-        and (all($components[]; has("name") and has("file") and has("context")))
-        and ($platforms | type == "string");
-        verify_structure
-        | if . then true else false end
-        ')
-        if [ ${verify} == 'true' ]; then
-          echo "✅ $GITHUB_WORKSPACE/.github/docker-build-config.json file is valid"
-          components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
-          platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
-        else
-          echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid"
-          echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
-          exit 1
-        fi
-        echo "components=${components}" >> $GITHUB_OUTPUT
-        echo "platforms=${platforms}" >> $GITHUB_OUTPUT
+      - name: Load Docker Configuration
+        id: load_component
+        run:  |
+          verify=$(cat "$GITHUB_WORKSPACE/.github/docker-build-config.json" | jq '
+          def verify_structure:
+          .components as $components
+          | .platforms as $platforms
+          | ($components | type == "array")
+          and (all($components[]; has("name") and has("file") and has("context")))
+          and ($platforms | type == "string");
+          verify_structure
+          | if . then true else false end
+          ')
+          if [ ${verify} == 'true' ]; then
+            echo "✅ $GITHUB_WORKSPACE/.github/docker-build-config.json file is valid"
+            components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+          else
+            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid"
+            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          echo "components=${components}" >> $GITHUB_OUTPUT
+          echo "platforms=${platforms}" >> $GITHUB_OUTPUT
 
   docker-check-build:
     needs: [load-docker-build-components, check-tag]
@@ -89,6 +91,10 @@ jobs:
       matrix:
         component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
     steps:
+      - name: Get version for current component
+        id: get-version
+        run: |
+          echo "IMAGE=${{ matrix.component.name }}" >> $GITHUB_ENV
       - name: Docker build
         uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.3
         with:
@@ -97,9 +103,10 @@ jobs:
           dry-run: true
           component: ${{ toJson(matrix.component) }}
           platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
-          tags: "test-${{ inputs.release }}"
+          tags: "${{ env.IMAGE_VERSION }}"
         env:
           GITHUB_TOKEN: ${{ github.token }}
+
   chart-release-prepare:
     needs: [check-tag, load-docker-build-components, docker-check-build]
     runs-on: ubuntu-latest
@@ -121,19 +128,9 @@ jobs:
       - name: "Debug"
         run: |
           echo "Images versions: ${{ steps.update-versions.outputs.images-versions }}"
-  tag:
-    needs: [chart-release-prepare]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Create release tag
-        uses: netcracker/qubership-workflow-hub/actions/tag-action@v1.0.3
-        with:
-          tag-name: "v${{ inputs.release }}"
-          ref: "release-${{ inputs.release }}"
-          create-tag: true
-          check-tag: false
+
   docker-build:
-    needs: [tag, chart-release-prepare, load-docker-build-components]
+    needs: [chart-release-prepare, load-docker-build-components]
     runs-on: ubuntu-latest
     strategy:
       fail-fast: true
@@ -148,7 +145,7 @@ jobs:
       - name: Docker build
         uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.3
         with:
-          ref: v${{ inputs.release }}
+          ref: release-${{ inputs.release }}
           download-artifact: false
           dry-run: false
           component: ${{ toJson(matrix.component) }}
@@ -158,8 +155,8 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
 
   charts-release:
-    needs: [tag, docker-build]
-    continue-on-error: true
+    needs: [docker-build]
+    continue-on-error: false
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -174,10 +171,13 @@ jobs:
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
 
       - name: Run chart-releaser
+        #continue-on-error: true
         uses: netcracker/chart-releaser-action@main
         with:
           charts_dir: charts/helm
-          release_name_template: "v{{ .Version }}"
+          release_name_template: "{{ .Version }}"
+          skip_existing: true
+          skip_upload: true
         env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 
@@ -187,23 +187,14 @@ jobs:
           config-name: release-drafter-config.yml
           publish: true
           name: ${{ inputs.release }}
-          tag: v${{ inputs.release }}
-          version: v${{ inputs.release }}
+          tag: ${{ inputs.release }}
+          version: ${{ inputs.release }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  upload-assets:
-    needs: [charts-release]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          ref: v${{ inputs.release }}
-
       - name: Upload Assets
         uses: netcracker/qubership-workflow-hub/actions/assets-action@main
         with:
-          item-path: './docs'
-          tag: v${{ inputs.release }}
+          tag: ${{ inputs.release }}
+          item-path: .cr-release-packages/*.tgz
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
