feat(ci): broadcast-files workflow rework

diff --git a/.github/workflows/broadcast-files.yaml b/.github/workflows/broadcast-files.yaml
--- a/.github/workflows/broadcast-files.yaml
+++ b/.github/workflows/broadcast-files.yaml
@@ -1,209 +1,91 @@
 ---
 name: Broadcast files to organization
+run-name: "${{ inputs.config-file }}. ${{ inputs.section }} files broadcast to ${{ inputs.repos || 'all repositories' }}"
 on:
-  # push:
-  #   branches:
-  #     - main
-  #   paths:
-  #     - 'config/linters/**'
-  #     - '.github/super-linter.env'
-  #     - 'workflow-templates/**'
-  #     - 'config/examples/auto-labeler-config.yaml'
-  #     - 'config/examples/release-drafter-config.yml'
-  #     - 'config/dependabot/cloud-core/dependabot.yml'
-  #     - '.gitattributes'
-  #     - '.editorconfig'
-  #     - '.github/auto-labeler-config.yaml'
   workflow_dispatch:
     inputs:
-      repo_name:
+      repos:
         description: |
-          Target repository name.
+          Target repositorys names. Comma-separated
           If not provided, the action will be triggered for all repositories in the organization.
         required: false
         type: string
-      replicate-common-config-files:
-        description: 'Replicate common config files'
-        required: false
-        default: false
-        type: boolean
-      replicate-common-workflows:
-        description: 'Replicate common workflows'
-        required: false
-        default: false
-        type: boolean
-      replicate-common-files:
-        description: 'Replicate common files'
-        required: false
-        default: false
-        type: boolean
-      replicate-cloud-core-dependabot:
-        description: 'Replicate dependabot config file for Cloud-Core repos'
-        required: false
-        default: false
-        type: boolean
-      replicate-superlinter-configs:
-        description: 'Replicate superlinter settings'
-        required: false
-        default: false
-        type: boolean
-      replicate-ossf-workflow:
-        description: 'Replicate OSSF workflow'
-        required: false
-        default: false
-        type: boolean
+      config-file:
+        description: 'Config file relative path'
+        required: true
+        type: string
+        default: '.github/broadcast-files-config.yaml'
+      section:
+        description: 'Name of the dict in config file'
+        required: true
+        type: string
+
 permissions:
   contents: read
   pull-requests: write
   statuses: read
 jobs:
-  replicate_common_files:
-    name: Replicating common git files
-    if: ${{ inputs.replicate-common-files }}
+  setup_jobs:
+    runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.setup_matrix.outputs.matrix }}
+      config: ${{ steps.setup_matrix.outputs.config }}
+    steps:
+      - uses: actions/checkout@v4
+      - id: setup_matrix
+        run: |
+          if [[ "${{ inputs.repos }}" != "" ]]; then
+            CSV_STRING="${{ inputs.repos }}"
+            JSON_MATRIX=$(jq -c -n --arg in_str "$CSV_STRING" '$in_str | split(",")')
+            echo "matrix=$JSON_MATRIX"
+            echo "matrix=$JSON_MATRIX" >> $GITHUB_OUTPUT
+          else
+            echo "matrix=[\"\"]"
+            echo "matrix=[\"\"]" >> $GITHUB_OUTPUT
+          fi
+          if [[ -f "${{ inputs.config-file }}" ]]; then
+            wget -q https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O yq
+            chmod +x yq
+            sudo mv yq /usr/local/bin/yq
+            if [[ "${{ inputs.section }}" != "" ]]; then
+              settings=$(yq eval ".${{ inputs.section }}" "${{ inputs.config-file }}" -o=json | jq -c '{settings: .}')
+            else
+              echo "::error::Config file section not specified!"
+              echo "[ERROR]: Config file section not specified!" >> $GITHUB_STEP_SUMMARY
+              exit 1
+            fi
+            echo "config=$settings" >> $GITHUB_OUTPUT
+          else
+            echo "::error::Config file '${{ inputs.config-file }}' not found."
+            echo "[ERROR]: Config file '${{ inputs.config-file }}' not found." >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+
+  replicate_files:
+    needs: setup_jobs
+    name: Replicating files
+    strategy:
+      fail-fast: false
+      matrix:
+        repo: ${{ fromJson(needs.setup_jobs.outputs.matrix) }}
+      max-parallel: 10
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-      - name: Replicating common files
-        uses: derberg/manage-files-in-multiple-repositories@v2
+      - name: Replicating files
+        uses: borislavr/manage-files-in-multiple-repositories@main
         with:
           github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
           exclude_private: true
-          exclude_forked: true
-          committer_username: NetcrackerCLPLCI
-          bot_branch_name: broadcast-common-files
-          patterns_to_include: >
-            .gitattributes, .editorconfig
-          destination: .
-          commit_message: 'chore: update of common files'
-  replicate_common_config_files:
-    name: Replicating common config files
-    if: ${{ inputs.replicate-common-config-files }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Replicating common config files
-        uses: derberg/manage-files-in-multiple-repositories@v2
-        with:
-          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
-          exclude_private: true
-          exclude_forked: true
-          committer_username: NetcrackerCLPLCI
-          bot_branch_name: broadcast-config-files
-          patterns_to_include: >
-            config/examples/auto-labeler-config.yaml,
-            config/examples/release-drafter-config.yml
-          destination: .github/
-          repos_to_ignore: >
-            KubeMarine, k8s-conformance, gatekeeper-library,
-            cassandra-exporter, pg_hint_plan
-          commit_message: 'chore: update of common config files'
-  replicate_superlinter_configs:
-    if: ${{ inputs.replicate-superlinter-configs }}
-    name: Replicate Super-Linter config files
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Replicating file
-        uses: derberg/manage-files-in-multiple-repositories@v2
-        with:
-          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
-          patterns_to_include: '.github/super-linter.env,.github/linters'
-          exclude_private: true
-          exclude_forked: true
-          committer_username: NetcrackerCLPLCI
-          bot_branch_name: broadcast-superliner
-          commit_message: 'chore: [skip ci] update of superlinter config files'
-  replicate_common_workflows:
-    if: ${{ inputs.replicate-common-workflows }}
-    name: Replicate commont workflow
-    runs-on: ubuntu-latest
-    # needs: [replicate_common_config_files, replicate_superlinter_configs]
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Replicating common workflows
-        uses: derberg/manage-files-in-multiple-repositories@v2
-        with:
-          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
-          patterns_to_include: >
-            workflow-templates/cla.yaml,
-            workflow-templates/super-linter.yaml,
-            workflow-templates/profanity-filter.yaml,
-            workflow-templates/automatic-pr-labeler.yaml,
-            workflow-templates/pr-conventional-commits.yaml,
-            workflow-templates/pr-lint-title.yaml,
-            workflow-templates/link-checker.yaml
-            workflow-templates/ossf-scorecard.yaml
-          destination: .github/workflows
-          repos_to_ignore: >
-            KubeMarine, k8s-conformance, gatekeeper-library,
-            cassandra-exporter, pg_hint_plan
-          exclude_private: true
-          exclude_forked: true
-          committer_username: NetcrackerCLPLCI
-          bot_branch_name: broadcast-workflows
-          commit_message: 'chore: update of common workflows'
-  replicate_ossf_workflow:
-    if: ${{ inputs.replicate-ossf-workflow }}
-    name: Replicate OSSF workflow
-    runs-on: ubuntu-latest
-    # needs: [replicate_common_config_files, replicate_superlinter_configs]
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Replicating common workflows
-        uses: derberg/manage-files-in-multiple-repositories@v2
-        with:
-          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
-          patterns_to_include: >
-            workflow-templates/ossf-scorecard.yaml
-          topics_to_include: qubership-ossf-request
-          destination: .github/workflows
-          exclude_private: true
-          exclude_forked: true
-          committer_username: NetcrackerCLPLCI
-          bot_branch_name: broadcast-ossf-workflow
-          commit_message: 'chore: update of common workflows'
-  replicate_cloud_core_dependabot:
-    if: ${{ inputs.replicate-cloud-core-dependabot }}
-    name: Replicate dependabot config file for Cloud-Core repos
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Replicating file
-        uses: derberg/manage-files-in-multiple-repositories@v2
-        with:
-          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
-          patterns_to_include: 'config/dependabot/cloud-core/dependabot.yml'
-          destination: .github/
-          exclude_private: true
-          exclude_forked: true
-          topics_to_include: core
-          committer_username: NetcrackerCLPLCI
-          bot_branch_name: broadcast-dependabot-configs
-          commit_message: 'chore: update cloud-core dependabot config file'
-  obsoleted_workflow_cleanup:
-    name: Obsoleted workflows cleanup
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Obsoleted workflow cleanup
-        uses: derberg/manage-files-in-multiple-repositories@v2
-        with:
-          github_token: '${{ secrets.GH_ACCESS_TOKEN }}'
-          patterns_to_remove:  >
-            pr-collect-commit-messages.yaml
-            prettier.yaml
-          repos_to_ignore: >
-            KubeMarine, k8s-conformance, gatekeeper-library,
-            cassandra-exporter, pg_hint_plan
-          exclude_private: true
-          exclude_forked: true
-          committer_username: NetcrackerCLPLCI
-          bot_branch_name: broadcast-workflows-cleanup
-          commit_message: 'chore: cleanup of obsoleted workflows'
+          exclude_forked: false
+          committer_username: borislavr
+          bot_branch_name: ${{ fromJson(needs.setup_jobs.outputs.config).settings.bot_branch_name || 'broadcast-files' }}
+          patterns_to_include: ${{ fromJson(needs.setup_jobs.outputs.config).settings.patterns_to_include || '' }}
+          topics_to_include: ${{ fromJson(needs.setup_jobs.outputs.config).settings.topics_to_include || '' }}
+          destination: ${{ fromJson(needs.setup_jobs.outputs.config).settings.destination || '.' }}
+          commit_message: ${{ fromJson(needs.setup_jobs.outputs.config).settings.commit_message || 'broadcasted files' }}
+          repo_name: ${{ matrix.repo }}
+          patterns_to_ignore: ${{ fromJson(needs.setup_jobs.outputs.config).settings.patterns_to_ignore || '' }}
+          patterns_to_remove: ${{ fromJson(needs.setup_jobs.outputs.config).settings.patterns_to_remove || '' }}
+          repos_to_ignore: ${{ fromJson(needs.setup_jobs.outputs.config).settings.repos_to_ignore || '' }}
