fix: topics-file validation step added to wf

diff --git a/.github/workflows/topics.yaml b/.github/workflows/topics.yaml
--- a/.github/workflows/topics.yaml
+++ b/.github/workflows/topics.yaml
@@ -18,23 +18,25 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      # Step 2: Set up the GitHub CLI
-      - name: Install GH CLI
-        uses: dev-hanz-ops/install-gh-cli-action@v0.2.1
-        with:
-            gh-cli-version: 2.65.0 # optional, see action.yml for current default
-
-      # Step 3: Authenticate with GitHub CLI
+      # Step 2: Authenticate with GitHub CLI
       - name: Authenticate GitHub CLI
         env:
           GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
         run: gh auth setup-git
+      # Step 3 Validate json file
+      - name: Validate repositoryName fields
+        run: |
+            INVALID_ENTRIES=$(jq -r '.[] | select(.repositoryName | contains(",")) | .repositoryName' "$JSON_FILE")
 
-      # Step 4: Install jq for JSON processing
-      - name: Install jq
-        run: sudo apt-get install -y jq
-
-      # Step 5: Update repository topics
+            if [ -n "$INVALID_ENTRIES" ]; then
+            echo "Invalid repositoryName entries found:"
+            echo "$INVALID_ENTRIES"
+            echo "Please ensure each repositoryName contains only one value."
+            exit 1
+            else
+            echo "All repositoryName fields are valid."
+            fi
+      # Step 3: Update repository topics
       - name: Update Topics
         env:
           GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
