feat: add option to replace existing topics in workflow

diff --git a/.github/workflows/topics.yaml b/.github/workflows/topics.yaml
--- a/.github/workflows/topics.yaml
+++ b/.github/workflows/topics.yaml
@@ -11,6 +11,11 @@ on:
         description: "Specific repository to update (leave empty to update all)"
         required: false
         default: ""
+      replace:
+        description: "Replace existing topics (leave empty to add topics)"
+        type: boolean
+        required: false
+        default: false
 permissions:
   contents: read
 
@@ -61,6 +66,12 @@ jobs:
             fi
 
             echo "Updating topics for $REPO_NAME: $TOPICS"
+
+            if [ "${{ github.event.inputs.replace }}" = "true" ]; then
+                echo "Replacing topics for $REPO_NAME"
+                gh repo edit "$GH_ORG/$REPO_NAME" --topics "" || echo "::warning ::Error to clean topics $REPO_NAME. Skipping."
+             fi
+
             gh repo edit "$GH_ORG/$REPO_NAME" --add-topic "$TOPICS" || echo "::warning ::Error updating $REPO_NAME. Skipping."
 
           else
@@ -75,9 +86,14 @@ jobs:
               fi
 
               echo "Updating topics for $REPO_NAME: $TOPICS"
-              if ! gh repo edit "$GH_ORG/$REPO_NAME" --add-topic "$TOPICS"; then
-                echo "::warning ::Error updating $REPO_NAME. Skipping."
-              fi
+
+            if [ "${{ github.event.inputs.replace }}" = "true" ]; then
+                echo "Replacing topics for $REPO_NAME"
+                gh repo edit "$GH_ORG/$REPO_NAME" --topics "" || echo "::warning ::Error to clean topics $REPO_NAME. Skipping."
+             fi
+
+            gh repo edit "$GH_ORG/$REPO_NAME" --add-topic "$TOPICS" || echo "::warning ::Error updating $REPO_NAME. Skipping."
+
             done
           fi
         env:
